### ISSUE TITLE
Autowiring services based on the types they implement is deprecated

### ISSUE THREAD

**Issue by roberto910907** [stwe/DatatablesBundle#731] opened 2018-01-10 23:09 UTC
Deprecations call in symfony profiler.

![code](https://user-images.githubusercontent.com/12180771/34800285-14c281aa-f631-11e7-905b-dd8528655244.png)

Fixed in FOSUserBundle [here](https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2595/commits/7a8c73cc9ba98a78523b69f53b8b2dfa6cb93781)

**Comment by Seb33300** [comment] 2018-01-10 23:39
Are you using dev-master?

**Comment by roberto910907** [comment] 2018-01-11 00:22
@Seb33300 Yes I do, `"sg/datatablesbundle": "dev-master"`and `**sf 3.3.15**`, adding in [SgDatatablesExtension](https://github.com/stwe/DatatablesBundle/blob/e0a31ea35894c88a28521d0946a780c3d387575f/DependencyInjection/SgDatatablesExtension.php#L30) ```
$container->setAlias('Sg\DatatablesBundle\Datatable\DatatableFactory', new Alias('sg_datatables.factory', false));
        $container->setAlias('Sg\DatatablesBundle\Response\DatatableResponse', new Alias('sg_datatables.response', false));
```
Solve the warning deprecations.

**Comment by ProfM2** [comment] 2018-01-11 22:21
I ran into the same thing in my code, but I was able to modify my code to not use the autowiring call based on the type, thereby eliminating this issue.  I had to fix the call in my controller, and services.yaml

**Comment by Seb33300** [comment] 2018-01-12 10:47
What did you do to have this deprecation notices?
I am using this bundle on `dev-master` branch with SF 3.4 but I can't reproduce this.

**Comment by ProfM2** [comment] 2018-01-12 21:18
My *OLD* code was circa Symfony 3.0 to 3.3, which was upgraded to 3.4 in my code above.

My services.yaml (from 3.3):

        app.datatable.plan:
            class: AppBundle\Datatables\PlanDatatable
            autowire: false
            autoconfigure: false
            public: true
            parent: sg_datatables.datatable.abstract

In my situation, it was how I was calling the bundle, pre-autowiring.  I was able to make it work based on a few examples I saw online - not necessarily based on what is recommended.

**Comment by faktotum85** [comment] 2018-04-24 13:10
I ran into this problem too - in my case I was able to solve it by adding Sg\DatatablesBundle\Datatable\DatatableFactory and Sg\DatatablesBundle\Datatable\DatatableResponse to my services.yml like this: 

```
services:
    Sg\DatatablesBundle\Datatable\DatatableFactory:
    Sg\DatatablesBundle\Datatable\DatatableResponse:
```

**Comment by stwe** [comment] 2021-04-05 10:16
wontfix

**Closed by stwe** 2021-04-05 10:16 UTC
