### ISSUE TITLE
Issues with string order

### ISSUE THREAD

**Issue by bettinz** [stwe/DatatablesBundle#441] opened 2016-08-22 09:31 UTC
Hello, I'm ordering a table with multiple parameters like this:
```php
'order' => array(
                array(
                    3, 'desc'
                ),
                array(
                    8, 'desc',
                ),
                array(
                    7, 'desc'
                ),
                array(
                    6, 'desc'
                ),
                array(
                    5, 'desc'
                ),
                array(
                    4, 'desc'
                )
            ),
```
The error appear only on some tables

![1st image](https://cloud.githubusercontent.com/assets/9438037/17850064/cce241a4-685b-11e6-8016-07213c7e61d5.png)

1st image

_edit_: after updating to latest dev-master and updating datatables to 1.10.12 the first problem with multiple columns appear solved (see second and third images ). With booleans seems broken (first image)

<img width="690" alt="punteggio 83" src="https://cloud.githubusercontent.com/assets/9438037/18012577/76095edc-6bba-11e6-99dd-f71c43113d00.png">
2nd image
<img width="664" alt="punteggio 86" src="https://cloud.githubusercontent.com/assets/9438037/18012578/764213d0-6bba-11e6-94f5-aa529a4d58f4.png">
3rd image

**Comment by bettinz** [comment] 2016-08-27 16:28
edit: one table is still not working. 
```json
{"draw":1,"recordsTotal":736,"recordsFiltered":2,"data":[{"id":798,"a":"98","b":"99","c":"95","total":"292","notes":"-","videoA":null,"videoB":null,"videoC":null,"qualified":true,"conductor":{"id":2,"name":"Claudia","surname":"Bacchi    "},"dog":{"id":2,"name":"Louis Woelfenkaste"},"work":{"id":6,"name":"IPO 3"},"sg_datatables_editable":{"0":false,"1":false,"2":false,"3":false,"4":false,"5":false,"6":false,"7":false,"9":false,"10":false,"11":false,"12":false},"sg_datatables_actions":{"13":{"show_video_a":false,"show_video_b":false,"show_video_c":false},"14":{"delete_work_result":true,"edit_work_result":true}}},{"id":799,"a":"94","b":"98","c":"100","total":"292","notes":"-","videoA":null,"videoB":null,"videoC":null,"qualified":true,"conductor":{"id":2,"name":"Claudia","surname":"Bacchi    "},"dog":{"id":6,"name":"Eiko von Weinbergblick"},"work":{"id":6,"name":"IPO 3"},"sg_datatables_editable":{"0":false,"1":false,"2":false,"3":false,"4":false,"5":false,"6":false,"7":false,"9":false,"10":false,"11":false,"12":false},"sg_datatables_actions":{"13":{"show_video_a":false,"show_video_b":false,"show_video_c":false},"14":{"delete_work_result":true,"edit_work_result":true}}}]}
```
![schermata 2016-08-27 alle 18 27 06](https://cloud.githubusercontent.com/assets/9438037/18028611/f4dd2422-6c83-11e6-8385-2c3657840ad9.png)

```php

'order' => array(
                array(
                    3, 'desc'
                ),
                array(
                    8, 'desc',
                ),
                array(
                    7, 'desc'
                ),
                array(
                    6, 'desc'
                ),
                array(
                    5, 'desc'
                ),
                array(
                    4, 'desc'
                )
            ),
```

**Comment by bettinz** [comment] 2016-08-27 22:28
I've found the issue:
if I use this code:
```php
/**
     * @var int
     *
     * @ORM\Column(name="total", type="string", nullable=true)
     */
    private $total;
```
and the type is string, the generated json is:
```json
"total":"292"
```
it's still a number, but it's considered as a string; with this code:
```php
/**
     * @var int
     *
     * @ORM\Column(name="total", type="integer", nullable=true)
     */
    private $total;
```
the json is

```json
"total":292
```
and it's a number. I need to save the attribute as a string, and I've tried with option "type" in datatable
```php
->add('total', 'column', array(
                'title' => 'Total',
                'type'=>'num'
            ))
```
and I've tried with number, numeric and num (I haven't find any doc about value of type) but nothing change. Do you have any hint?

**Comment by stwe** [comment] 2016-08-30 17:46
The 'type' option does not work . This option has no effect since the ordering and search actions are performed by a server-side script.

What would you like sort ? Give me a reproducible example.

**I tried without error:**
Column A - string in json result
Column B - string in json result

```
            'order' => array(
                array(6, 'asc'),
                array(7, 'desc')
            )
```

**Comment by bettinz** [comment] 2016-08-30 18:07
For example: "10", "11", "20", "100", "300" ordered by string will return:
"10", "11", "100", "20", "300" because they are seen as string instead of numbers. 

Another example (desc):
"total":"292", "110", "10",  "100"
"total":292, 110, 100, 10

In the first case they are strings, in the second case they are numbers
https://datatables.net/forums/discussion/2526/sorting-integers
http://stackoverflow.com/questions/7572685/sort-string-items-in-a-datatable-as-int-using-c-sharp

**Comment by stwe** [comment] 2016-09-03 14:55
For that I must implement a "cast to int " option for the query . 
Can take a while....

**Comment by bettinz** [comment] 2016-09-03 14:59
Isn't bettere to allow the user to choose the type? For example, I can choose that a column is integer or string in datatable; I can always select "interger" for "aaa", but this return error or doesn't order because of course "aaa" isn't a number.
But, if I have a column called results with number and it's a string, I can always add a character like "?" or "NA". Btw, it's not urgent and maybe I'm the only one with this request 😄

**Comment by Bruce17** [comment] 2016-10-12 10:45
I provided a fix for this in PR https://github.com/stwe/DatatablesBundle/pull/480.

**Comment by dnagirl** [comment] 2016-10-12 15:04
Rather than implementing a `cast int` method, it might be better to allow the user to set the sort function. The option could take a PHP function name like `asort` or a closure.

**Comment by Bruce17** [comment] 2016-10-12 16:13
@dnagirl 
Your suggestion works only if you load all data into the PHP application. But if you have e.g. a set of 40.000 rows in your database, it's a bad idea to load everything into your application and then do sorting.

Let the database do the work for what it was designed for: sorting and returning data.

**Closed** 2016-10-19 17:05 UTC
Labels: feature
