### ISSUE TITLE
Problem dateTimeColumn in export

### ISSUE THREAD

**Issue by teger** [stwe/DatatablesBundle#911] opened 2019-08-06 15:52 UTC
I have a problem with the DateTimeColumn in export.
I have a column DateTimeColumn and in the datatable, the view is OK.
But with export (CSV, Excel, Copy,..), the exported column DateTimeColumn is empty.

Thanks for your help.

PHP : 7.0.33
Symfony 3.4.30

SGDatatables : 1.0.3

**Comment by witzkito** [comment] 2019-08-21 22:03
Something similar happens to me.
In the view the DateTimeColumn is Ok, but in export shows the script in @SgDatatables/render/datetime.html.twig.

> $(function() {             moment.locale("es");                              $("#sg-datatables-alumno_datatable-datetime-e5a540e4668389b83ef466c6dad87c4f86abcae2").html(moment.unix(743396400).format("L"));                     });

**Comment by stephanvierkant** [comment] 2019-08-22 13:22
DateTimeColumns are rendered client side, so we've to change it to server side rendering. PR's are more than welcome!

> PHP : 7.0.33
offtopic, but nevertheless: are you really running a PHP version that's unsupported for a very long time?

**Comment by mshd** [comment] 2019-09-26 10:18
As a fix just create a file under
 app/Resources/SgDatatablesBundle/views/render/datetime.html.twig 


{# the special '!' prefix avoids errors when extending from an overridden template
 extends "@!SgDatatablesBundle/Resources/views/render/datetime.html.twig" %} #}
{%- set datetime_id_selector -%}
    sg-datatables-{{ datatable_name }}-datetime-{{ row_id }}
{%- endset -%}

{%- set datetime_selector -%}
    id="{{ datetime_id_selector }}"
{%- endset -%}

{% if column_class_editable_selector is defined %}
    <div {{ datetime_selector }} class="{{ column_class_editable_selector }}" data-pk="{{ pk }}" {% if path is not same as(null) %}data-path="{{ path }}"{% endif %}></div>
{% else %}
    <div {{ datetime_selector }}>
        {% if data is same as(null) and default_content is not same as(null) %}
            {{ default_content }}
        {% endif %}
    </div>
{% endif %}

{% if data is not same as(null) and data|date("Y") > 10 %}
    {{ data|date("yyyy-mm-dd H:i") }}
{% endif %}

[SgDatatablesBundle.zip](https://github.com/stwe/DatatablesBundle/files/3657269/SgDatatablesBundle.zip)

**Comment by Seb33300** [comment] 2020-03-23 13:41
Duplicate of https://github.com/stwe/DatatablesBundle/issues/594

**Closed by Seb33300** 2020-03-23 13:41 UTC
