### ISSUE TITLE
What if my column needs data from an associated object, but the associated object is null?

### ISSUE THREAD

**Issue by Sluimers** [stwe/DatatablesBundle#754] opened 2018-03-23 14:17 UTC
Suppose I have the following code:

PersonDatatable.php
```php
class PersonDatatable extends AbstractDatatable {
...
 $this->columnBuilder
...
->add('address.country', Column::class, array(
                'title' => 'Country'
            ))
...
```

If just one of the addresses is null, then the table cannot be rendered due to an error.
Is there a solution to this problem?

**Comment by Sluimers** [comment] 2018-03-23 15:42
Results in the same error for me.

**Comment by roxid** [comment] 2018-05-19 07:41
I was able to resolve this issue by setting the `default_content` on **every** association column. In your case those may look like `address.country`, `address.street`, `address.city` and so on. Make sure, to set `default_content` for every associated object property.

Note: The error message displayed in a js alert contained something like `Requested unknown parameter 'address.country' for row 0, column 4`. It will tell you the column you need to specify `default_content` for. The error is caused by the underlying data of that column  and row being `null` or `undefined`. So in your case the property `country` of an `address` object of at least one of your entities listed in the datatable may be `null`.

If you did not see that error message but another one instead, please tell us.

**Comment by Seb33300** [comment] 2018-06-09 17:22
@Sluimers Are you sure this error occurs on a `Column` class?

It seems that I am able to reproduce it on a `DateTimeColumn`, but not on a `Column`

**Comment by Seb33300** [comment] 2018-06-09 18:20
It seems this can happen on `Column` when the column is editable.

I just pushed a fix on `dev-master`.
Can you confirm it solves your issue?

**Closed** 2021-04-05 10:17 UTC
