### ISSUE TITLE
LengthMenu "all" omits one item from the total result

### ISSUE THREAD

**Issue by Snowbell92** [stwe/DatatablesBundle#432] opened 2016-08-09 06:17 UTC
Hello,
I'm using the following configuration:

    $this->options->set(array(
            'display_start' => 0,
            'defer_loading' => -1,
            'dom' => 'lfiprtip',
            'length_menu' => array(10, 25, 50, 100,-1),
            'order_classes' => true,
            'order' => array(array(0, 'asc')),
            'order_multi' => true,
            'page_length' => 20,
            'paging_type' => Style::FULL_NUMBERS_PAGINATION,
            'renderer' => '',
            'scroll_collapse' => false,
            'search_delay' => 0,
            'state_duration' => 7200,
            'stripe_classes' => array(),
            'class' => Style::BOOTSTRAP_3_STYLE,
            'individual_filtering' => true,
            'individual_filtering_position' => 'head',
            'use_integration_options' => true,
            'force_dom' => true,
        )); 

The "all" option is `lengthMenu` is missing one content. The count is correct, but the last item isn't visible in the table. see the below screenshots: 

this is the result count when I am showing 50 items: 
![50](https://cloud.githubusercontent.com/assets/338241/17506507/2c5faba2-5e2b-11e6-9068-b01c36f7e87b.PNG)

and this is the count when I am showing all items (no pagination, but one item short): 
![all](https://cloud.githubusercontent.com/assets/338241/17506514/3b2c4f0a-5e2b-11e6-83ba-ee2fa5eb68ed.PNG)

am I doing anything wrong? or is it a bug?

**Comment by stwe** [comment] 2016-08-09 10:19
show me your controller code

**Comment by Snowbell92** [comment] 2016-08-11 03:53
@stwe sorry about the delay. Here's the code: 

    <?php

     namespace Bbd\BongoAppBundle\Datatables;

     use Bbd\BongoAppBundle\Entity\Content;
     use Sg\DatatablesBundle\Datatable\View\AbstractDatatableView;
     use Sg\DatatablesBundle\Datatable\View\Style;

     /**
      * Class ContentDatatable.
     */
    class ContentDatatable extends AbstractDatatableView
     {
    /**
     * {@inheritdoc}
     */
    public function buildDatatable(array $options = array())
    {
        /*$this->topActions->set(array(
            'start_html' => '<div class="row"><div class="col-sm-3">',
            'end_html' => '<hr></div></div>',
            'actions' => array(
                array(
                    'route' => $this->router->generate('content_new'),
                    'label' => $this->translator->trans('datatables.actions.new'),
                    'icon' => 'entypo-plus',
                    'attributes' => array(
                        'rel' => 'tooltip',
                        'title' => $this->translator->trans('datatables.actions.new'),
                        'class' => 'btn btn-primary',
                        'role' => 'button',
                    ),
                ),
            ),
        ));*/

        $this->features->set(array(
            'auto_width' => true,
            'defer_render' => false,
            'info' => true,
            'jquery_ui' => false,
            'length_change' => true,
            'ordering' => true,
            'paging' => true,
            'processing' => true,
            'scroll_x' => false,
            'scroll_y' => '',
            'searching' => true,
            'state_save' => false,
            'delay' => 0,
            'extensions' => array(),

        ));

        $this->ajax->set(array(
            'url' => $this->router->generate(('content_results')),
            'type' => 'GET',
            'pipeline' => 10,

        ));

        $this->options->set(array(
            'display_start' => 0,
            'defer_loading' => -1,
            'dom' => 'lfiprtip',
            'length_menu' => array(20, 50, 100, 1000, 10000,'"All"'),
            'order_classes' => true,
            'order' => array(array(0, 'asc')),
            'order_multi' => true,
            'page_length' => 20,
            'paging_type' => Style::FULL_NUMBERS_PAGINATION,
            'renderer' => '',
            'scroll_collapse' => false,
            'search_delay' => 0,
            'state_duration' => 7200,
            'stripe_classes' => array(),
            'class' => Style::BOOTSTRAP_3_STYLE,
            'individual_filtering' => true,
            'individual_filtering_position' => 'head',
            'use_integration_options' => true,
            'force_dom' => true,
        ));
        $categories = $this->em->getRepository('BbdBongoAppBundle:Category')->findAll();
        $contentOwner = $this->em->getRepository('BbdBongoAppBundle:ContentOwner')->findAll();

        $this->columnBuilder

            ->add(null, 'multiselect', array(
                'start_html' => '<div class="wrapper" id="testwrapper">',
                'end_html' => '</div>',
                'add_if' => function () {
                    return $this->authorizationChecker->isGranted('ROLE_ADMIN');
                },
                'class' => 'row-sort',

                'actions' => array(
                    /*array(
                        'route' => 'content_bulk_delete',
                        'label' => 'Delete',

                        'icon' => 'entypo-cancel',
                        'attributes' => array(
                            'rel' => 'tooltip',
                            'title' => 'Delete',
                            'class' => 'btn btn-primary btn-xs',
                            'role' => 'button',
                        ),
                    ),*/

                ),
            ))
            ->add('title', 'column', array('title' => 'Title', 'filter' => array('text', array(
                'search_type' => 'eq',
            )), 'class' => 'row-title'))

            ->add('content_owner.slug', 'column', array('title' => 'O', 'class' => 'row-owner',
                'filter' => array('select2', array(
                    'select_options' => array('' => 'All') + $this->getCollectionAsOptionsArray($contentOwner, 'slug', 'slug'),
                    'search_type' => 'eq',
                    'multiple' => true,
                    'class' => 'chosen-select',
                )), ))
            ->add('sequence', 'column', array('title' => 'S/P/E', 'class' => 'row-spe',
                'filter' => array('select2', array(
                    'select_options' => array('Single' => 'Single',
                        'Episode' => 'Episode',
                        'Part' => 'Part',
                    ),
                    'search_type' => 'eq',
                    'multiple' => true,
                    'class' => 'chosen-select',
                )), ))
            //->add('sequence_count', 'column', array('title' => 'Seq', 'class' => 'row-sequence'))
            ->add('category.slug', 'column', array('title' => 'Cat', 'class' => 'row-cat',
                'filter' => array('select2', array(
                    'select_options' => array('' => 'All') + $this->getCollectionAsOptionsArray($categories, 'slug', 'slug'),
                    'search_type' => 'eq',
                    'multiple' => true,
                    'class' => 'chosen-select',
                )), ))
            //->add('category_sequence', 'column', array('title' => 'Cat Seq', 'class' => 'row-seq'))
            ->add('unique_id', 'column', array('title' => 'Unique ID', 'class' => 'row-uid'))
            ->add('priority', 'column', array('title' => 'P', 'class' => 'row-priority',
                'filter' => array('select2', array(
                    'select_options' => array('' => 'All') + Content::get2priority(),
                    'search_type' => 'eq',
                    'multiple' => true,
                    'class' => 'chosen-select',
                )), ))
            ->add('status', 'column', array('title' => 'Status', 'class' => 'row-status',
                'filter' => array('select2', array(
                    'select_options' => array(
                        '' => 'All',
                        'Listed' => 'Listed',
                        'Negotiating' => 'Negotiating',
                        'Signed' => 'Signed',
                        'Received Q' => 'Received Q',
                        'Received NA' => 'Received NA',
                        'Converted' => 'Converted',
                        'Ready' => 'Ready',
                    ),
                    'search_type' => 'eq',
                    'multiple' => true,
                    'class' => 'chosen-select',
                )), ))
            ->add('system_id', 'column', array(
                'title' => 'Bongo ID',
            ))
            ->add('youtube_id', 'column', array(
                'title' => 'YouTube ID',
            ))
            ->add('qc_status', 'boolean', array(
                'title' => 'QC',
                'class' => 'row-qc',
            ))
            ->add('created_at', 'datetime', array(
                'title' => 'Created',
            ))
            ->add('kaltura_id', 'column', array('title' => 'Kaltura', 'class' => 'row-kaltura'))

            ->add(null, 'action', array(
                'title' => $this->translator->trans('datatables.actions.title'),
                'actions' => array(
                    array(
                        'route' => 'content_show',
                        'route_parameters' => array(
                            'id' => 'id',
                        ),
                        'label' => $this->translator->trans('datatables.actions.show'),
                        'icon' => 'entypo-eye',
                        'attributes' => array(
                            'rel' => 'tooltip',
                            'title' => $this->translator->trans('datatables.actions.show'),
                            'class' => 'btn btn-info m-r-xs btn-xs',
                            'role' => 'button',
                        ),
                    ),
                    array(
                        'route' => 'content_edit',
                        'route_parameters' => array(
                            'id' => 'id',
                        ),
                        'label' => $this->translator->trans('datatables.actions.edit'),
                        'icon' => 'entypo-minus-squared',
                        'attributes' => array(
                            'rel' => 'tooltip',
                            'title' => $this->translator->trans('datatables.actions.edit'),
                            'class' => 'btn btn-default btn-xs',
                            'role' => 'button',
                        ),
                    ),
                ),
            ))
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function getEntity()
    {
        return 'Bbd\BongoAppBundle\Entity\Content';
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'content_datatable';
    }
    }

**Comment by stwe** [comment] 2016-08-14 08:56
And your Controller code?

**Comment by Snowbell92** [comment] 2016-08-15 13:37
@stwe controller:

    <?php

    /*
     *
     * (c) Ahmad Sajid <ahmad@bongobd.com
     *
     * For the full copyright and license information, please view the LICENSE
     * file that was distributed with this source code.
     */

     namespace Bbd\BongoAppBundle\Controller;

     use Symfony\Bundle\FrameworkBundle\Controller\Controller;
     use Symfony\Component\HttpFoundation\Request;
     use Symfony\Component\HttpFoundation\JsonResponse;
     use Symfony\Component\HttpFoundation\Response;
     use Symfony\Component\Form\FormEvents;
     use Symfony\Component\Form\FormEvent;
     use Doctrine\Common\Collections\ArrayCollection;
     use Bbd\BongoAppBundle\Entity\Album;
     use Bbd\BongoAppBundle\Entity\Content;
     use Bbd\BongoAppBundle\Entity\Comment;
     use Bbd\BongoAppBundle\Form\ContentType;
     use Bbd\BongoAppBundle\Form\CastAndCrewType;
     use Bbd\BongoAppBundle\Form\SynopsisType;
     use Bbd\BongoAppBundle\Form\ContentComment;
     use Bbd\BongoAppBundle\Form\ContentAssigment;

     class ContentController extends Controller
    {
    /**
     * @var array
     */
    protected $tabs = array(
        'general' => array(
            'title' => 'General',
            'aria' => 'home',
            'role' => 'ROLE_CONTENT_GENERAL',
        ),
        'synopsis' => array(
            'title' => 'Synopsis',
            'aria' => 'profile',
            'role' => 'ROLE_CONTENT_SYNOPSIS',
        ),
        'cast' => array(
            'title' => 'Cast & Crew',
            'aria' => 'messages',
            'role' => 'ROLE_CONTENT_CAST_AND_CREW',
        ),
        'graphics' => array(
            'title' => 'Graphics',
            'aria' => 'settings',
            'role' => 'ROLE_CONTENT_GRAPHICS',
        ),
        'legal' => array(
            'title' => 'Legal',
            'aria' => 'settings',
            'role' => 'ROLE_CONTENT_LEGAL',
        ),
        'comments' => array(
            'title' => 'Comments/Log',
            'aria' => 'settings',
            'role' => 'ROLE_CONTENT_GENERAL',
        ),
    );

    /**
     * @return \Symfony\Component\Security\Core\Authorization\AuthorizationChecker
     */
    protected function getAutorizationChecker()
    {
        return $this->get('security.authorization_checker');
    }

    /**
     * Lists all Content entities.
     */
    public function indexAction()
    {
        $datatable = $this->get('bbd_datatables.content');
        $datatable->buildDatatable();

        return $this->render('BbdBongoAppBundle:Content:index.html.twig', array(
            'datatable' => $datatable,
        ));
    }

    /**
     * @return Response
     */
    public function indexResultsAction()
    {
        $datatable = $this->get('bbd_datatables.content');
        $datatable->buildDatatable();

        $query = $this->get('sg_datatables.query')->getQueryFrom($datatable);

        return $query->getResponse();
    }

    /**
     * Creates a new Content entity.
     */
    public function createAction(Request $request)
    {
        $entity = new Content();
        $form = $this->createEditForm($entity, $this->generateUrl('content_create'), 'POST', 'Create');
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();

            $comment = new Comment();
            $comment->setType('Auto Genrated');
            $comment->setValue('Content created by '.$this->getUser()->getUsername());
            $entity->addComment($comment);

            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('content_show', array('id' => $entity->getId())));
        }

        return $this->render('BbdBongoAppBundle:Content:new.html.twig', array(
                    'entity' => $entity,
                    'form' => $form->createView(),
                    'tabs' => $this->tabs,
        ));
    }

    /**
     * Displays a form to create a new Content entity.
     */
    public function newAction()
    {
        $entity = new Content();
        $form = $this->createEditForm($entity, $this->generateUrl('content_create'), 'POST', 'Create');

        return $this->render('BbdBongoAppBundle:Content:new.html.twig', array(
                    'entity' => $entity,
                    'form' => $form->createView(),
                    'tabs' => $this->tabs,
        ));
    }

    /**
     * Finds and displays a Content entity.
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $repository = $em->getRepository('BbdBongoAppBundle:Content');

        $entity = $repository->find($id);
        $synopsis = $em->getRepository('BbdBongoAppBundle:Synopsis')->getSynopsisByContentId($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Content entity.');
        }

        $deleteForm = $this->createDeleteForm($id);

        return $this->render('BbdBongoAppBundle:Content:show.html.twig', array(
                    'entity' => $entity,
                    'log' => $repository->getCommentsAndAssigments($entity),
                    'synopsis' => $synopsis,
                    'delete_form' => $deleteForm->createView(),
                    'tabs' => $this->tabs,
        ));
    }

    /**
     * Displays a form to edit an existing Content entity.
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $repository = $em->getRepository('BbdBongoAppBundle:Content');
        $entity = $repository->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Content entity.');
        }

        $editForm = $this->createEditForm($entity, $this->generateUrl('content_update', array('id' => $entity->getId())), 'PUT', 'Update');
        $deleteForm = $this->createDeleteForm($id);

        return $this->render('BbdBongoAppBundle:Content:edit.html.twig', array(
                    'entity' => $entity,
                    'log' => $repository->getCommentsAndAssigments($entity),
                    'edit_form' => $editForm->createView(),
                    'delete_form' => $deleteForm->createView(),
                    'tabs' => $this->tabs,
        ));
    }

    /**
     * Creates a form to edit a Content entity.
     *
     * @param Content $content     The entity
     * @param string  $action
     * @param string  $method
     * @param string  $updateLabel
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createEditForm(Content $content, $action, $method, $updateLabel)
    {
        $form = $this->createFormBuilder(null, array(
                    'action' => $action,
                    'method' => $method,
                ))
                ->add('content', new ContentType(), array(
                    'data' => $content,
                ))
                ->add('cast', new CastAndCrewType($this->getDoctrine()->getManager()), array(
                    'data' => $content,
                ))
                ->add('synopsis', new SynopsisType(), array(
            'data' => $content->getSynopsis(),
        ));
        if ($updateLabel != 'Create') {
            $form->add('comments', new ContentComment());
        }

        $grantedAssigment = $this->get('security.context')->isGranted('ROLE_ADMIN');
        if ($updateLabel != 'Create' && $grantedAssigment) {
            $form->add('assigment', new ContentAssigment());
        }
        $form->add('submit', 'submit', array('label' => $updateLabel));

        $form->get('cast')->remove('submit');

        $em = $this->getDoctrine()->getManager();
        $form->addEventListener(FormEvents::POST_SUBMIT, function (FormEvent $event) use ($content, $em, $updateLabel) {
            $albums = explode('-==|==-', $event->getForm()->get('content')->get('albums')->getData());
            foreach ($content->getAlbums() as $contentAlbum) {
                $contentAlbum->removeContent($content);
            }
            foreach ($albums as $album) {
                if (!trim($album)) {
                    continue;
                }
                $matches = array();
                if (preg_match('/^new\|\|\|(.+)$/', $album, $matches)) {
                    $eAlbum = new Album();
                    $eAlbum->setName($matches[1]);

                    $em->persist($eAlbum);
                } else {
                    $eAlbum = $em->find('BbdBongoAppBundle:Album', $album);
                }

                $eAlbum->addContent($content);
            }

            $synopsis = $event->getForm()->get('synopsis')->getData();
            $content->setSynopsis($synopsis);

            if ($updateLabel != 'Create') {
                $comment = $event->getForm()->get('comments')->getData();
                $comment->getType() && $content->addComment($comment);
            }

            if ($event->getForm()->has('assigment')) {
                $assigment = $event->getForm()->get('assigment')->getData();
                $assigment->getType() && $content->addAssigment($assigment);
            }
        });

        return $form->getForm();
    }

    /**
     * Edits an existing Content entity.
     */
    public function updateAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $repository = $em->getRepository('BbdBongoAppBundle:Content');
        /** @var $content Content */
        $content = $repository->find($id);

        if (!$content) {
            throw $this->createNotFoundException('Unable to find Content entity.');
        }

        $originalEpisodes = new ArrayCollection();

        foreach ($content->getEpisodes() as $episode) {
            $originalEpisodes->add($episode);
        }

        $deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createEditForm($content, $this->generateUrl('content_update', array('id' => $content->getId())), 'PUT', 'Update');
        $editForm->handleRequest($request);

        if ($editForm->isValid()) {
            $files = $request->files->get('form');
            foreach ($files['content'] as $key => $file) {
                if (!empty($file)) {
                    $newAsset[$key] = $this->get('bongoapp.assetService')->postContent($id, $key, $file);
                }
            }
            foreach ($originalEpisodes as $episode) {
                if (false === $content->getEpisodes()->contains($episode)) {
                    // remove the Task from the Tag
                    $em->remove($episode);
                    $em->flush();
                }
            }

            $em->flush();

            return $this->redirect($this->generateUrl('content_show', array('id' => $id)));
        }

        return $this->render('BbdBongoAppBundle:Content:edit.html.twig', array(
                    'entity' => $content,
                    'log' => $repository->getCommentsAndAssigments($content),
                    'edit_form' => $editForm->createView(),
                    'delete_form' => $deleteForm->createView(),
                    'tabs' => $this->tabs,
        ));
    }

    /**
     * Deletes a Content entity.
     */
    public function deleteAction(Request $request, $id)
    {
        $form = $this->createDeleteForm($id);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity = $em->getRepository('BbdBongoAppBundle:Content')->find($id);

            if (!$entity) {
                throw $this->createNotFoundException('Unable to find Content entity.');
            }
            $this->get('bongoapp.assetService')->deleteBySystemId($entity->getSystemId(), 'artist');
            try {
                $em->remove($entity);
            } catch (\Exception $e) {
                dump($e->getMessage());
            }

            $em->flush();
        }

        return $this->redirect($this->generateUrl('content'));
    }

    /**
     * Creates a form to delete a Content entity by id.
     *
     * @param mixed $id The entity id
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm($id)
    {
        return $this->get('form.factory')
                        ->createNamedBuilder('delete', 'form')
                        ->setAction($this->generateUrl('content_delete', array('id' => $id)))
                        ->setMethod('DELETE')
                        ->add('submit', 'submit', array('label' => 'Delete'))
                        ->getForm()
        ;
    }

    /**
     * Autocomplete content origin.
     *
     * @param Request $request
     * @param int     $id
     *
     * @return JsonResponse
     */
    public function autocompleteOriginsAction(Request $request, $id)
    {
        $term = $request->request->get('term');

        $em = $this->getDoctrine()->getManager();

        $qb = $em->createQueryBuilder()
                ->select('c.title as id, c.title as text')
                ->from('BbdBongoAppBundle:Content', 'c')
                ->where('c.id != :id')
                ->setParameter('id', $id);

        if ($term) {
            foreach (preg_split('/\s+/', trim($term)) as $i => $word) {
                $qb->andWhere('c.title LIKE :word'.$i)
                        ->setParameter('word'.$i, '%'.$word.'%');
            }
        }

        $titles = $qb
                ->orderBy('c.title')
                ->setMaxResults(10)
                ->getQuery()
                ->getArrayResult();

        return new JsonResponse($titles);
    }

    /**
     * Autocomplete content albums.
     *
     * @param Request $request
     *
     * @return JsonResponse
     */
    public function autocompleteAlbumsAction(Request $request)
    {
        $term = $request->request->get('term');

        $em = $this->getDoctrine()->getManager();

        $qb = $em->createQueryBuilder()
                ->select('a.id, a.name as text')
                ->from('BbdBongoAppBundle:Album', 'a');

        if ($id = $request->request->get('id')) {
            return new JsonResponse(
                    $qb
                            ->where('a.id = :id')
                            ->setParameter('id', (int) $id)
                            ->getQuery()
                            ->getOneOrNullResult()
            );
        }

        if ($term) {
            foreach (preg_split('/\s+/', trim($term)) as $i => $word) {
                $qb->andWhere('a.name LIKE :word'.$i)
                        ->setParameter('word'.$i, '%'.$word.'%');
            }
        }

        $titles = $qb
                ->orderBy('a.name')
                ->setMaxResults(10)
                ->getQuery()
                ->getArrayResult();

        return new JsonResponse($titles);
    }

    /**
     * Generate CSV  content.
     *
     * @param Request $request
     *
     * @return response
     *
     * @todo it;s dirty solution for quick and fast export as csv, need to refactor with proper solution.
     */
    public function generateWpCsvAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        $data = $request->query->get('data');
        $choices = explode(',', $data);

        $contents = $em->getRepository('BbdBongoAppBundle:Content')->getWpCsv($choices);

        $filename = 'export_'.date('Y_m_d_His').'.csv';

        $response = $this->render('BbdBongoAppBundle:Content:export.html.twig', array('data' => $contents));

        $response->setStatusCode(200);
        $response->headers->set('Content-Encoding', 'UTF-8');
        $response->headers->set('Content-Type', 'text/csv; charset=UTF-8');
        $response->headers->set('Content-Description', 'Submissions Export');
        $response->headers->set('Content-Disposition', 'attachment; filename='.$filename);
        $response->headers->set('Content-Transfer-Encoding', 'binary');
        $response->headers->set('Pragma', 'no-cache');
        $response->headers->set('Expires', '0');
        echo "\xEF\xBB\xBF";

        return $response;

        /* return $this->render('BbdBongoAppBundle:Content:export.html.twig', array(
          'data' => $contents,
          )); */
    }

    /**
     * Delete action.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function bulkDeleteAction(Request $request)
    {
        $isAjax = $request->isXmlHttpRequest();

        if ($isAjax) {
            $choices = $request->request->get('data');
            $em = $this->getDoctrine()->getManager();
            $repository = $em->getRepository('BbdBongoAppBundle:Content');

            foreach ($choices as $choice) {
                $entity = $repository->find($choice);

                $em->remove($entity);
            }

            $em->flush();

            return new Response('Success', 200);
        }

        return new Response('Bad Request', 400);
    }

    /**
     * Generate CSV  content.
     *
     * @param Request $request
     *
     * @return response
     *
     * @todo it;s dirty solution for quick and fast export as csv, need to refactor with proper solution.
     */
    public function generateCsvAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        $data = $request->query->get('data');

        $choices = explode(',', $data);

        /*
         * @todo refactor and make one function for enabling cache for web and disable for export
         */
        $contents = $em->getRepository('BbdBongoAppBundle:Content')->expotCsvContent($choices);
        $episodes = $em->getRepository('BbdBongoAppBundle:Episode')->getEpisodeList();

        $episodesByContent = array();
        foreach ($episodes as $episode) {
            if (!array_key_exists($episode['content_id'], $episodesByContent)) {
                $episodesByContent[$episode['content_id']] = array();
            }
            $episodesByContent[$episode['content_id']][] = $episode;
        }

        $data = array();

        foreach ($contents as &$content) {
            $content['created_at'] = $content['created_at']->format('d-M-Y');

            $data[] = $content;

            if (isset($episodesByContent[$content['id']])) {
                foreach ($episodesByContent[$content['id']] as &$episode) {
                    $episode['priority'] = $content['priority'];
                    $episode['owner'] = $content['owner'];
                    $episode['sequence'] = $content['sequence'];
                    $episode['category'] = $content['category'];
                    $episode['category_sequence'] = $content['category_sequence'];
                    $episode['created_at'] = $content['created_at'];
                    $episode['media'] = $content['media'];
                    $episode['album'] = $content['album'];

                    $data[] = $episode;
                }
            }
        }

        $filename = 'export_'.date('Y_m_d_His').'.csv';

        $response = $this->render('BbdBongoAppBundle:Content:exportdb.html.twig', array('data' => $data));

        $response->setStatusCode(200);
        $response->headers->set('Content-Encoding', 'UTF-8');
        $response->headers->set('Content-Type', 'text/csv; charset=UTF-8');
        $response->headers->set('Content-Description', 'Submissions Export');
        $response->headers->set('Content-Disposition', 'attachment; filename='.$filename);
        $response->headers->set('Content-Transfer-Encoding', 'binary');
        $response->headers->set('Pragma', 'no-cache');
        $response->headers->set('Expires', '0');
        // echo "\xEF\xBB\xBF";

        return $response;

        /* return $this->render('BbdBongoAppBundle:Content:exportdb.html.twig', array(
          'data' => $data,
          )); */
    }

    /**
     * @return JsonResponse
     */
    public function findContentsAction()
    {
        $limit = 80;
        $name = $this->getRequest()->query->get('q');
        $contentData = $this->getDoctrine()->getManager()
                        ->getRepository('BbdBongoAppBundle:Content')->getContentsByName($name, $limit);
        $dto = [];
        foreach ($contentData as $content) {
            $dto[] = [
                'id' => $content['id'],
                'text' => $content['title'],
            ];
        }

        return new JsonResponse($dto);
    }

    /**
     * @return JsonResponse
     */
    public function findContentsByNameAction()
    {
        $limit = 80;
        $name = $this->getRequest()->query->get('q');
        $contentData = $this->getDoctrine()->getManager()
            ->getRepository('BbdBongoAppBundle:Content')->getContentsByName($name, $limit);
        $dto = [];
        foreach ($contentData as $content) {
            $dto[] = [
                'id' => $content['id'],
                'text' => $content['title'],
            ];
        }

        return new JsonResponse(['items' => $dto]);
    }

    /**
     * @param $id
     *
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function kalturaImageAction($id)
    {
        $this->get('bongoapp.assetService')->postContent($id, 'landscape', null);

        return $this->redirect($this->generateUrl('content_show', array('id' => $id)));
    }
    }

**Comment by stwe** [comment] 2016-08-15 19:35
You should try :

```
'length_menu' => array(20, 50, 100, 1000, 10000, -1),
```

**Comment by Snowbell92** [comment] 2016-08-16 05:45
still the same thing. the last item is missing.

**Comment by stwe** [comment] 2016-08-16 10:23
Please:

1) change your page_length option to one of a value from your length_menu array. Example:

```
'length_menu' => array(20, 50, 100, 1000, 10000, -1),
'page_length' => 20,
```

2) clear your cache
3) look at firebug. This is the right config:

![unbenannt](https://cloud.githubusercontent.com/assets/2964748/17696008/f626898a-63ab-11e6-83cc-eea5ccd853d7.JPG)

for me it is working properly

**Comment by stwe** [comment] 2016-08-19 18:51
@Snowbell92 I close the issue, because I can not reproduce the error. Sorry.

**Closed by stwe** 2016-08-19 18:51 UTC
Labels: can't reproduce, support question
